// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LCM.Repositories.Models;

public partial class Evidence
{
    public int ID { get; set; }

    public string Sourcer { get; set; }

    public int Page { get; set; }

    public DateOnly QuoteDate { get; set; }

    public DateOnly ExpirationDate { get; set; }

    public string Updater { get; set; }

    public DateTime UpdateTime { get; set; }

    public virtual ICollection<PnEvidence> PnEvidence { get; set; } = new List<PnEvidence>();
}