// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LCM.Repositories.Models;

public partial class PnEvidence
{
    public int ID { get; set; }

    public int PnPriceID { get; set; }

    public int EvidenceID { get; set; }

    public int? Item { get; set; }

    public string Remark { get; set; }

    public string Updater { get; set; }

    public DateTime UpdateTime { get; set; }

    public virtual Evidence Evidence { get; set; }

    public virtual PnPrice PnPrice { get; set; }
}