// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LCM.Repositories.Models;

public partial class PnPrice
{
    public int ID { get; set; }

    public string PartNumber { get; set; }

    public string Org { get; set; }

    public DateOnly Month { get; set; }

    public string Sourcer { get; set; }

    public decimal ImputMarketPrice { get; set; }

    public string Updater { get; set; }

    public DateTime UpdateTime { get; set; }

    public int StatusID { get; set; }

    public virtual ICollection<PnEvidence> PnEvidence { get; set; } = new List<PnEvidence>();

    public virtual Status Status { get; set; }
}