// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LCM.Repositories.Models;

public partial class PoStatusDesc
{
    public int ID { get; set; }

    public string Description { get; set; }

    public virtual ICollection<XxPor0001_Resell> XxPor0001_Resell { get; set; } = new List<XxPor0001_Resell>();
}