// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace LCM.Repositories.Models;

public partial class XxPor0001_Resell
{
    public int ID { get; set; }

    public string PENo { get; set; }

    public string OrderNo { get; set; }

    public string SOLine { get; set; }

    public string PartNo { get; set; }

    public int Quantity { get; set; }

    public decimal NetPrice { get; set; }

    public DateOnly ShipmentDate { get; set; }

    public DateOnly SystemUpdateDate { get; set; }

    public string Updater { get; set; }

    public DateTime UpdateTime { get; set; }

    public int? StatusID { get; set; }

    public string ProcureRemark { get; set; }

    public string VendorRemark { get; set; }

    public virtual ICollection<Xx_Po_Receipt> Xx_Po_Receipt { get; set; } = new List<Xx_Po_Receipt>();
}